version: '3'
services:
  web:
    restart: always
    build: .
    container_name: fmamily-finance
    tty: true
    stdin_open: true
    working_dir: '/workspace/'
    volumes:
      - .bashrc:/root/.bashrc:ro
      - .:/workspace