version: "3"
services:
    web:
        restart: always
        build: .
        container_name: family-finance
        # command: python family-finance.py
        tty: true
        stdin_open: true
        working_dir: "/workspace/"
        volumes:
            - .bashrc:/root/.bashrc:ro
            - .:/workspace
        # environment:
        #     PYTHONDONTWRITEBYTECODE: 1
        #     PROJECT_ID: ${PROJECT_ID}
        #     PRIVATE_KEY_ID: ${PRIVATE_KEY_ID}
        #     PRIVATE_KEY: ${PRIVATE_KEY}
        #     CLIENT_EMAIL: ${CLIENT_EMAIL}
        #     CLIENT_ID: ${CLIENT_ID}
        #     CLIENT_X509_CERT_URL: ${CLIENT_X509_CERT_URL}
    # app:
    #     command: python family-finance.py
    #     depends_on:
    #         web:
    #             condition: service_healthy
