version: "3"
services:
    web:
        restart: always
        build:
            context: .
            args:
                - UID
                - GID
                - USERNAME=user
                - GROUPNAME=user
        container_name: family-finance
        tty: true
        stdin_open: true
        working_dir: "/workspace/"
        volumes:
            - .bashrc:/home/user/.bashrc:ro
            - .:/workspace
        env_file:
            - .env
