#!/bin/bash

echo "DISCODE_BOT_TOKEN_FAMILYFINANCE = $DISCODE_BOT_TOKEN_FAMILYFINANCE" >> .env

echo "MFEMAIL = $MFEMAIL" >> .env
echo "MFPASSWORD = $MFPASSWORD" >> .env
echo "TWO_STEP_AUTHENTICATION_CODE = $TWO_STEP_AUTHENTICATION_CODE" >> .env
