#!/bin/bash

echo "DISCODE_BOT_TOKEN_FAMILYFINANCE = $DISCODE_BOT_TOKEN_FAMILYFINANCE" >> .env

# CREDENTIALS
echo "PROJECT_ID = $PROJECT_ID" >> .env
echo "PRIVATE_KEY_ID = $PRIVATE_KEY_ID" >> .env
echo "PRIVATE_KEY = $PRIVATE_KEY" >> .env
echo "CLIENT_EMAIL = $CLIENT_EMAIL" >> .env
echo "CLIENT_ID = $CLIENT_ID" >> .env
echo "CLIENT_X509_CERT_URL = $CLIENT_X509_CERT_URL" >> .env
